spring.application.name=SS10-Exma

spring.datasource.url=jdbc:mysql://localhost:3306/ss10_exam?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true